### ISSUE TITLE
.md links should be .html

### ISSUE THREAD

**Issue by cpursley** [arch-js/arch-js.github.io#2]
On the the first page of the docs, _...(read more about [the reasoning](http://arch-js.github.io/docs/07-livescript.md) behind the decision)..._ and in several other places, links point towards the [.md](http://arch-js.github.io/docs/07-livescript.md) file instead of the [.html](http://arch-js.github.io/docs/07-livescript.html) version. Additionally, there are several links which are not pointing at the correct resource.

**Comment by robbiemccorkell** [comment]
Yea sorry, I've been meaning to sort out all of the relative URLs for ages and been super busy. I'll try and look at it soon!

**Comment by cpursley** [comment]
@robbiemccorkell ~ I don't mind patching them with a little direction. [Archbot](https://github.com/archbot) keeps the github site in sync with the repo, right? Also, perhaps pulling docs out into their own repo is another approach.

**Comment by robbiemccorkell** [comment]
Yea we started by saying the docs in the main arch repo would be the main 'source of truth' for the docs. So when a commit is made to master in that repo, it runs this deployment script to modify the markdown slightly and commit them to here (with archbot's credentials) https://github.com/arch-js/arch/blob/master/circle-build-docs.sh

It seems like Facebook are using a similar pattern for their doc sites. But yea, we might want to pull the docs out somewhere else to make things simpler. 

So I guess we just need an extra step in that shell script (or in a separate script in another language) that runs a regex on the docs to find the links and replace them with something more useful.

**Comment by charypar** [comment]
I vote for keeping docs in the main repo so that they stay in sync with code. The question is what gets published, but we can manage that with tags and Github API imo.

**Comment by robbiemccorkell** [comment]
@asavin kindly just fixed this here: https://github.com/arch-js/arch/pull/97
